### ISSUE TITLE
Is it possible to upload image with its original name 

### ISSUE THREAD

**Issue by MahmadSharaf** [jvsteiner/s3-image-uploader#12]
Thank you for the awesome plugin, it is very convenient. I have been using it for aw while at found a difficulty in maintenance. For example, the image got uploaded but I lost the autogenerated url for some reason. In that case, it is so hard to find this image.

Another case, if I would like to uploaded an already existing one.

**Comment by jvsteiner** [comment]
the file name in the bucket is just the md5 hash of the image contents.  this is done for a few good reasons:
1) its simpler, since I don't have to check and see if there is already a file there by the same name, in case different pictures with the same name are uploaded.
2) in case the same file does get uploaded but with a different name, more storage space is not used, and previous links to the same picture continue to work.
3) uploading the same picture multiple times is idempotent.

The downside is that filenames are not particularly memorable.

I assume that the user has admin control over the s3 bucket being used, so I do not see the downsides as too big.

Do you have a suggestion for a feature or different implementation?

**Comment by MahmadSharaf** [comment]
No, on the contrary, your approach is better than I wished. I didn't know that it uses images (or any other file type, I assume) md5 hash. And thus, will avoid reuploading an image or file or even figuring out a name for the file.

Now, it is up to me to find a way to display the uploaded images in the Cloudflare R2 Bucket.

Again, thank you for the awesome plugin and the speedy response.
