### ISSUE TITLE
Mobile Device Support

### ISSUE THREAD

**Issue by DavidBoettger** [jvsteiner/s3-image-uploader#9]
Hello jvsteiner,

First of all, I want to express my gratitude to you for creating such an amazing plugin.

It is, as far as I can tell, the only one that even supports the installation on mobile devices (iPad Pro in my case).

However, I cant seem to get the image upload process working on mobile. I am certain that I am either doing something wrong or this feature could easily be implemented because it does actually work with the Imgur plugin that you were inspired by.

I would be extremely thankful if we could look into this issue as it would make my workflow much easier.
(As of now, I have to save the files on my server separately when I am at University and later upload them with my Windows PC and the plugin when I am at home.)

Whenever I try to paste an image into my vault right now, it simply does nothing.

I am hoping for your support and would be happy to test out different things and versions to get it working.

**Comment by jvsteiner** [comment]
hmm, might have had a regression - will need to take a look

**Comment by jvsteiner** [comment]
So I took a look at this, and it works on my device (iOS 17.1.2).

Could you please provide detailed steps to reproduce?  On iPhone, if at all possible, since I do not have access to an Android for testing.

**Comment by jvsteiner** [comment]
closing this as stale

**Comment by DavidBoettger** [comment]
Hello and sorry for the late reply.

I just tested it on iPadOS 17.2 and it still doesn't work. When I try to paste an image, nothing happens. The image is not being uploaded to the cloud nor is it pasted into the folder. It just doesn't show up. The same thing happens on my iPhone 13 Pro on IOS 17.2.

I have also confirmed that the problem is not caused by another plugin because I created a new vault and it didn't work there either.

I think there is still a bug present and am hoping this can be resolved.

I would be grateful for any suggestions on what to try next.

Best regards,
David

**Comment by jvsteiner** [comment]
It works on my iphone XS when pasting a photo from the camera roll.  that is the only way I tested it, and the only way that it is intended to be used.  I don't have an ipad, or a keyboard that I can attach (which it sounds like you have, since you mentioned key sequences).  Unfortunately I don't have a lot of good ideas on how to further try to reproduce, due to my lack of hardware.

**Comment by DavidBoettger** [comment]
I am totally fine with it just working from camera roll but I can't get it to work.
How is your procedure? Do you use the insert photo button in Obsidian or do you go into the photos app, copy the photo and then paste it into Obsidian?

**Comment by jvsteiner** [comment]
hmm, I was using the insert photo button...

**Comment by jvsteiner** [comment]
There is a problem with plugin on iOS.  It used to work, now it doesn't.  One possibility is that Apple has done something that interferes with plugins generally.  It's known that they have a problem with plugins that run executable code: https://developer.apple.com/forums/thread/68972

Also I don't have a good way to debug it.  

In conclusion, this is not something I will be working on.  If someone else wants to figure it out, and keep track of when it breaks due to iOS updates, I would be very happy to accept PR's
